upload:
  max_size_mb: 50
  allowed_extensions:
  - .pdf
  - .docx
  - .doc
  - .png
  - .jpg
  - .jpeg
  - .txt
  base_path: /Volumes/fouad_demos/information_extraction/sanabil_documents
database:
  host: instance-6308e8f8-a992-4de7-a85c-7beb1fdc8d8a.database.cloud.databricks.com
  port: 5432
  name: information_extractor
  user: sanabil_app
  schema: information_extraction
secrets:
  database_password:
    scope: information_extraction
    key: lakebase_db_password
databricks:
  output_table: fouad_demos.information_extraction.ai_parse_document_output
  job_id: 424554646032710
